
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: "Metrics Collector"
      Timeout: 600
      Handler: runner.handle_event
      Runtime: python2.7
      CodeUri: build
      Role: "arn:aws:iam::644160558196:role/custodian-mu"
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  Function:
    Description: Lambda Name
    Value: !Ref Function

