AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  LogExporter:
    Type: 'AWS::Serverless::Function'
    FunctionName: "c7n-flow-log-archiver"
    Description: "CloudWatch Logs S3 Archiver"
    MemorySize: 1024
    Timeout: 600
    Properties:
      Handler: exporter.handler
      Runtime: python2.7
      CodeUri: './stage'
      Role: "arn:aws:iam::644160558196:role/custodian-mu"
      Events:
        Stream:
	  Type: Kinesis
	  Properties:
            Stream: arn:aws:kinesis:us-east-1:123456789012:stream/my-stream
            StartingPosition: TRIM_HORIZON
            BatchSize: 100

Outputs:
  Function:
    Description: Exporter Lambda
    Value: !Ref LogExporter
